name: Check if generated files are up to date
on:
  pull_request:
jobs:
  check-generated:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - run: |
        # Generate files.
        make manifests generate credits

        # Check if the worktree is clean.
        git add .
        git diff --staged --quiet
