name: tagpr
on:
  push:
    branches:
    - main
jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v5
    - id: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - if: steps.tagpr.outputs.tag != ''
      name: Trigger release workflow
      uses: actions/github-script@v8
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: "release.yaml",
            ref: "refs/tags/${{ steps.tagpr.outputs.tag }}",
          })
